spring.application.name=SistemaTutorias

spring.datasource.url=jdbc:sqlserver://localhost:1433;database=SistemaTutorias27;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345

#Para actualizar las tablas de la BD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
